-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 15:07:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coperosystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coperosystem` ;

-- -----------------------------------------------------
-- Schema coperosystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coperosystem` DEFAULT CHARACTER SET utf8 ;
USE `coperosystem` ;

-- -----------------------------------------------------
-- Table `coperosystem`.`copoProductos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`copoProductos` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`copoProductos` (
  `productoID` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(35) NOT NULL,
  `enable` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`productoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`comisiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`comisiones` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`comisiones` (
  `comisionID` INT NOT NULL AUTO_INCREMENT,
  `active` BIT NOT NULL DEFAULT 1,
  `porcentaje` DECIMAL(3,2) NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  PRIMARY KEY (`comisionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`carritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`carritos` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`carritos` (
  `carritoID` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(4) NOT NULL,
  `color` VARCHAR(15) NOT NULL,
  `enable` BIT NOT NULL DEFAULT 1,
  PRIMARY KEY (`carritoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`coperos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`coperos` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`coperos` (
  `coperoID` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` INT NOT NULL,
  `cedula` VARCHAR(15) NOT NULL,
  `enable` BIT NOT NULL DEFAULT 1,
  `cuentaBancaria` VARCHAR(25) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  PRIMARY KEY (`coperoID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`playas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`playas` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`playas` (
  `playaID` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`playaID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`ventas` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`ventas` (
  `ventaID` INT NOT NULL AUTO_INCREMENT,
  `posttime` DATE NOT NULL,
  `tipopago` TINYINT(2) NOT NULL COMMENT '0 = Efectivo \n1 = Simpe\n2 = Tarjeta',
  `monto` INT NOT NULL,
  `montoComision` FLOAT NOT NULL,
  `vuelto` INT NOT NULL DEFAULT 0,
  `pagado` BIT NOT NULL DEFAULT 0,
  `comisionID` INT NOT NULL,
  `carritoID` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  `coperoID` INT NOT NULL,
  `ordergroup` VARCHAR(36) NOT NULL,
  `playaID` INT NOT NULL,
  PRIMARY KEY (`ventaID`),
  INDEX `fk_ventas_comisiones1_idx` (`comisionID` ASC) VISIBLE,
  INDEX `fk_ventas_carritos1_idx` (`carritoID` ASC) VISIBLE,
  INDEX `fk_ventas_coperos1_idx` (`coperoID` ASC) VISIBLE,
  INDEX `fk_ventas_playas1_idx` (`playaID` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_comisiones1`
    FOREIGN KEY (`comisionID`)
    REFERENCES `coperosystem`.`comisiones` (`comisionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_carritos1`
    FOREIGN KEY (`carritoID`)
    REFERENCES `coperosystem`.`carritos` (`carritoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_coperos1`
    FOREIGN KEY (`coperoID`)
    REFERENCES `coperosystem`.`coperos` (`coperoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_playas1`
    FOREIGN KEY (`playaID`)
    REFERENCES `coperosystem`.`playas` (`playaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`ingredientes` (
  `ingredienteID` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(35) NOT NULL,
  `enable` BIT NOT NULL DEFAULT 1,
  `medida` VARCHAR(45) NOT NULL,
  `stack` INT NOT NULL,
  PRIMARY KEY (`ingredienteID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`ingreXProdu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`ingreXProdu` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`ingreXProdu` (
  `cantidad` DECIMAL(7,2) NOT NULL,
  `enable` BIT NOT NULL DEFAULT 1,
  `ingredienteID` INT NOT NULL,
  `productoID` INT NOT NULL,
  INDEX `fk_IngresXProdu_Ingredientes1_idx` (`ingredienteID` ASC) VISIBLE,
  INDEX `fk_IngresXProdu_copo_productos1_idx` (`productoID` ASC) VISIBLE,
  CONSTRAINT `fk_IngresXProdu_Ingredientes1`
    FOREIGN KEY (`ingredienteID`)
    REFERENCES `coperosystem`.`ingredientes` (`ingredienteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_IngresXProdu_copo_productos1`
    FOREIGN KEY (`productoID`)
    REFERENCES `coperosystem`.`copoProductos` (`productoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`checkTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`checkTypes` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`checkTypes` (
  `checkTypeID` SMALLINT(2) NOT NULL AUTO_INCREMENT,
  `checkTypeName` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`checkTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`checkStatuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`checkStatuses` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`checkStatuses` (
  `checkStatusID` SMALLINT(2) NOT NULL AUTO_INCREMENT,
  `statusName` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`checkStatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`inventarioChecks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`inventarioChecks` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`inventarioChecks` (
  `icheckID` INT NOT NULL,
  `posttime` DATETIME NULL,
  `typeID` SMALLINT(2) NULL,
  `statusID` SMALLINT(2) NULL,
  `coperoID1` INT NOT NULL,
  `coperoID2` INT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  PRIMARY KEY (`icheckID`),
  INDEX `fk_inventarioChecks_checkTypes1_idx` (`typeID` ASC) VISIBLE,
  INDEX `fk_inventarioChecks_checkStatuses1_idx` (`statusID` ASC) VISIBLE,
  INDEX `fk_inventarioChecks_Coperos1_idx` (`coperoID1` ASC) VISIBLE,
  INDEX `fk_inventarioChecks_Coperos2_idx` (`coperoID2` ASC) VISIBLE,
  CONSTRAINT `fk_inventarioChecks_checkTypes1`
    FOREIGN KEY (`typeID`)
    REFERENCES `coperosystem`.`checkTypes` (`checkTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventarioChecks_checkStatuses1`
    FOREIGN KEY (`statusID`)
    REFERENCES `coperosystem`.`checkStatuses` (`checkStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventarioChecks_Coperos1`
    FOREIGN KEY (`coperoID1`)
    REFERENCES `coperosystem`.`coperos` (`coperoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventarioChecks_Coperos2`
    FOREIGN KEY (`coperoID2`)
    REFERENCES `coperosystem`.`coperos` (`coperoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`inventoryLogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`inventoryLogs` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`inventoryLogs` (
  `inventoryLogID` INT NOT NULL AUTO_INCREMENT,
  `posttime` DATETIME NOT NULL,
  `operationType` SMALLINT NOT NULL COMMENT '0 = Venta\n1 = Refill\n2= Open\n3= Close',
  `quantity` DECIMAL(7,2) NOT NULL,
  `checkID` INT NULL,
  `carritoID` INT NOT NULL,
  `coperoID` INT NULL,
  `ingredientesID` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  PRIMARY KEY (`inventoryLogID`),
  INDEX `fk_inventoryLogs_inventarioChecks1_idx` (`checkID` ASC) VISIBLE,
  INDEX `fk_inventoryLogs_ingrediente1_idx` (`ingredientesID` ASC) VISIBLE,
  INDEX `fk_inventoryLogs_carritos1_idx` (`carritoID` ASC) VISIBLE,
  INDEX `fk_inventoryLogs_coperos1_idx` (`coperoID` ASC) VISIBLE,
  CONSTRAINT `fk_inventoryLogs_inventarioChecks1`
    FOREIGN KEY (`checkID`)
    REFERENCES `coperosystem`.`inventarioChecks` (`icheckID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventoryLogs_ingrediente1`
    FOREIGN KEY (`ingredientesID`)
    REFERENCES `coperosystem`.`ingredientes` (`ingredienteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventoryLogs_carritos1`
    FOREIGN KEY (`carritoID`)
    REFERENCES `coperosystem`.`carritos` (`carritoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventoryLogs_coperos1`
    FOREIGN KEY (`coperoID`)
    REFERENCES `coperosystem`.`coperos` (`coperoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`precioBase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`precioBase` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`precioBase` (
  `productoID` INT NOT NULL,
  `precio` INT NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL,
  `active` BIT NOT NULL DEFAULT 1,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  INDEX `fk_precioBase_copoProductos1_idx` (`productoID` ASC) VISIBLE,
  CONSTRAINT `fk_precioBase_copoProductos1`
    FOREIGN KEY (`productoID`)
    REFERENCES `coperosystem`.`copoProductos` (`productoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`precioPorPlaya`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`precioPorPlaya` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`precioPorPlaya` (
  `playaID` INT NOT NULL,
  `productoID` INT NOT NULL,
  `precio` INT NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL,
  `active` BIT NOT NULL DEFAULT 1,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  INDEX `fk_precioPorPlaya_playas1_idx` (`playaID` ASC) VISIBLE,
  INDEX `fk_precioPorPlaya_copoProductos1_idx` (`productoID` ASC) VISIBLE,
  CONSTRAINT `fk_precioPorPlaya_playas1`
    FOREIGN KEY (`playaID`)
    REFERENCES `coperosystem`.`playas` (`playaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_precioPorPlaya_copoProductos1`
    FOREIGN KEY (`productoID`)
    REFERENCES `coperosystem`.`copoProductos` (`productoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`turnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`turnos` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`turnos` (
  `turnoID` INT NOT NULL AUTO_INCREMENT,
  `horaInicio` DATETIME NOT NULL,
  `HoraFinal` DATETIME NOT NULL,
  `carritoID` INT NOT NULL,
  `coperoID` INT NOT NULL,
  `playaID` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  PRIMARY KEY (`turnoID`),
  INDEX `fk_turno_carritos1_idx` (`carritoID` ASC) VISIBLE,
  INDEX `fk_turno_Coperos1_idx` (`coperoID` ASC) VISIBLE,
  INDEX `fk_turno_playas1_idx` (`playaID` ASC) VISIBLE,
  CONSTRAINT `fk_turno_carritos1`
    FOREIGN KEY (`carritoID`)
    REFERENCES `coperosystem`.`carritos` (`carritoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turno_Coperos1`
    FOREIGN KEY (`coperoID`)
    REFERENCES `coperosystem`.`coperos` (`coperoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turno_playas1`
    FOREIGN KEY (`playaID`)
    REFERENCES `coperosystem`.`playas` (`playaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`solicitudes` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`solicitudes` (
  `solicitudID` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `nota` VARCHAR(100) NULL,
  `location` POINT NOT NULL,
  `playaID` INT NOT NULL,
  `carritoID` INT NULL,
  PRIMARY KEY (`solicitudID`),
  INDEX `fk_solicitudes_playas1_idx` (`playaID` ASC) VISIBLE,
  INDEX `fk_solicitudes_carritos1_idx` (`carritoID` ASC) VISIBLE,
  CONSTRAINT `fk_solicitudes_playas1`
    FOREIGN KEY (`playaID`)
    REFERENCES `coperosystem`.`playas` (`playaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_carritos1`
    FOREIGN KEY (`carritoID`)
    REFERENCES `coperosystem`.`carritos` (`carritoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`statusSolicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`statusSolicitud` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`statusSolicitud` (
  `statusSolicitudID` INT NOT NULL,
  `statusName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`statusSolicitudID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`productoPorSolicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`productoPorSolicitud` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`productoPorSolicitud` (
  `productoID` INT NOT NULL,
  `solicitudID` INT NOT NULL,
  `cantidad` SMALLINT(1) NOT NULL,
  INDEX `fk_productoPorSolicitud_copoProductos1_idx` (`productoID` ASC) VISIBLE,
  INDEX `fk_productoPorSolicitud_solicitudes1_idx` (`solicitudID` ASC) VISIBLE,
  CONSTRAINT `fk_productoPorSolicitud_copoProductos1`
    FOREIGN KEY (`productoID`)
    REFERENCES `coperosystem`.`copoProductos` (`productoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productoPorSolicitud_solicitudes1`
    FOREIGN KEY (`solicitudID`)
    REFERENCES `coperosystem`.`solicitudes` (`solicitudID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`carritoStatuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`carritoStatuses` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`carritoStatuses` (
  `carritoStatusID` SMALLINT NOT NULL COMMENT '1 - DISPONIBLE\n2 - VENDIENDO \n3 - CERRANDO\n4 - HACIENDO CAMBIO',
  `statusName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`carritoStatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`ubicacionesCarrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`ubicacionesCarrito` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`ubicacionesCarrito` (
  `carritoID` INT NOT NULL,
  `gps` POINT NOT NULL,
  `updateAt` DATETIME NOT NULL,
  `carritoStatusID` SMALLINT NOT NULL,
  INDEX `fk_ubicacionesCarrito_carritos1_idx` (`carritoID` ASC) VISIBLE,
  INDEX `fk_ubicacionesCarrito_carritoStatuses1_idx` (`carritoStatusID` ASC) VISIBLE,
  CONSTRAINT `fk_ubicacionesCarrito_carritos1`
    FOREIGN KEY (`carritoID`)
    REFERENCES `coperosystem`.`carritos` (`carritoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ubicacionesCarrito_carritoStatuses1`
    FOREIGN KEY (`carritoStatusID`)
    REFERENCES `coperosystem`.`carritoStatuses` (`carritoStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`cajaCheck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`cajaCheck` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`cajaCheck` (
  `ccheckID` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `checkTypeID` SMALLINT(2) NULL,
  `checkStatusID` SMALLINT(2) NULL,
  `coperoID1` INT NOT NULL,
  `coperoID2` INT NOT NULL,
  `turnoID` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  PRIMARY KEY (`ccheckID`),
  INDEX `fk_cierresCaja_checkTypes1_idx` (`checkTypeID` ASC) VISIBLE,
  INDEX `fk_cierresCaja_checkStatuses1_idx` (`checkStatusID` ASC) VISIBLE,
  INDEX `fk_checkCaja_coperos1_idx` (`coperoID1` ASC) VISIBLE,
  INDEX `fk_checkCaja_coperos2_idx` (`coperoID2` ASC) VISIBLE,
  INDEX `fk_checkCaja_turnos1_idx` (`turnoID` ASC) VISIBLE,
  CONSTRAINT `fk_cierresCaja_checkTypes1`
    FOREIGN KEY (`checkTypeID`)
    REFERENCES `coperosystem`.`checkTypes` (`checkTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cierresCaja_checkStatuses1`
    FOREIGN KEY (`checkStatusID`)
    REFERENCES `coperosystem`.`checkStatuses` (`checkStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkCaja_coperos1`
    FOREIGN KEY (`coperoID1`)
    REFERENCES `coperosystem`.`coperos` (`coperoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkCaja_coperos2`
    FOREIGN KEY (`coperoID2`)
    REFERENCES `coperosystem`.`coperos` (`coperoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_checkCaja_turnos1`
    FOREIGN KEY (`turnoID`)
    REFERENCES `coperosystem`.`turnos` (`turnoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`pagosCoperos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`pagosCoperos` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`pagosCoperos` (
  `pagosCoperosID` INT NOT NULL AUTO_INCREMENT,
  `coperoID` INT NOT NULL,
  `monto` FLOAT NOT NULL,
  `posttime` DATETIME NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  INDEX `fk_pagosCoperos_coperos1_idx` (`coperoID` ASC) VISIBLE,
  PRIMARY KEY (`pagosCoperosID`),
  CONSTRAINT `fk_pagosCoperos_coperos1`
    FOREIGN KEY (`coperoID`)
    REFERENCES `coperosystem`.`coperos` (`coperoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`pagosVentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`pagosVentas` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`pagosVentas` (
  `pagosCoperosID` INT NOT NULL,
  `ventaID` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  INDEX `fk_pagosVentas_pagosCoperos1_idx` (`pagosCoperosID` ASC) VISIBLE,
  INDEX `fk_pagosVentas_ventas1_idx` (`ventaID` ASC) VISIBLE,
  CONSTRAINT `fk_pagosVentas_pagosCoperos1`
    FOREIGN KEY (`pagosCoperosID`)
    REFERENCES `coperosystem`.`pagosCoperos` (`pagosCoperosID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagosVentas_ventas1`
    FOREIGN KEY (`ventaID`)
    REFERENCES `coperosystem`.`ventas` (`ventaID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`solicitudesLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`solicitudesLog` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`solicitudesLog` (
  `solicitudLogID` INT NOT NULL AUTO_INCREMENT,
  `solicitudID` INT NOT NULL,
  `statusSolicitudID` INT NOT NULL,
  `posttime` DATETIME NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  PRIMARY KEY (`solicitudLogID`),
  INDEX `fk_solicitudesLog_solicitudes1_idx` (`solicitudID` ASC) VISIBLE,
  INDEX `fk_solicitudesLog_statusSolicitud1_idx` (`statusSolicitudID` ASC) VISIBLE,
  CONSTRAINT `fk_solicitudesLog_solicitudes1`
    FOREIGN KEY (`solicitudID`)
    REFERENCES `coperosystem`.`solicitudes` (`solicitudID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudesLog_statusSolicitud1`
    FOREIGN KEY (`statusSolicitudID`)
    REFERENCES `coperosystem`.`statusSolicitud` (`statusSolicitudID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`sources` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`sources` (
  `sourceID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `enable` BIT NOT NULL,
  PRIMARY KEY (`sourceID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`levels` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`levels` (
  `levelID` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `enable` BIT NOT NULL,
  PRIMARY KEY (`levelID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`eventTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`eventTypes` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`eventTypes` (
  `eventTID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `enable` BIT NOT NULL,
  PRIMARY KEY (`eventTID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`objectTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`objectTypes` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`objectTypes` (
  `objectTypeID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `enable` BIT NOT NULL,
  PRIMARY KEY (`objectTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coperosystem`.`eventLogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coperosystem`.`eventLogs` ;

CREATE TABLE IF NOT EXISTS `coperosystem`.`eventLogs` (
  `eventID` INT NOT NULL AUTO_INCREMENT,
  `posttime` DATETIME NOT NULL,
  `computer` VARCHAR(20) NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  `checksum` VARBINARY(150) NULL,
  `descripction` VARCHAR(80) NOT NULL,
  `reference1` VARCHAR(45) NOT NULL,
  `reference2` VARCHAR(45) NOT NULL,
  `value1` BIGINT NOT NULL,
  `value2` BIGINT NOT NULL,
  `enable` BIT NOT NULL,
  `sourceID` INT NOT NULL,
  `levelID` INT NOT NULL,
  `eventTID` INT NOT NULL,
  `objectTypeID` INT NOT NULL,
  PRIMARY KEY (`eventID`),
  INDEX `fk_eventLogs_sources1_idx` (`sourceID` ASC) VISIBLE,
  INDEX `fk_eventLogs_levels1_idx` (`levelID` ASC) VISIBLE,
  INDEX `fk_eventLogs_eventTypes1_idx` (`eventTID` ASC) VISIBLE,
  INDEX `fk_eventLogs_objectTypes1_idx` (`objectTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_eventLogs_sources1`
    FOREIGN KEY (`sourceID`)
    REFERENCES `coperosystem`.`sources` (`sourceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventLogs_levels1`
    FOREIGN KEY (`levelID`)
    REFERENCES `coperosystem`.`levels` (`levelID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventLogs_eventTypes1`
    FOREIGN KEY (`eventTID`)
    REFERENCES `coperosystem`.`eventTypes` (`eventTID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventLogs_objectTypes1`
    FOREIGN KEY (`objectTypeID`)
    REFERENCES `coperosystem`.`objectTypes` (`objectTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
